### ISSUE TITLE
NPM lezer-loader name

### ISSUE THREAD

**Issue by jared-hughes** [JoaoBrlt/lezer-webpack-loader#1]
Hi! I created lezer-loader (https://www.npmjs.com/package/lezer-loader) a while ago. The project where I was using it migrated from webpack to esbuild, so I haven't revisited it since.

If you want to take the npm name, I can transfer it to you. My latest release was 0.3.0, so if you do a 1.0, there shouldn't be problems with backwards-compatibility.

Though I suggest the README would suggest `test: /\.grammar$/i` instead of `test: /\.grammar/i`, so `.grammar.d.ts` etc doesn't get picked up.

My repo: https://github.com/jared-hughes/lezer-loader.

**Comment by JoaoBrlt** [comment]
Hi Jared!

Indeed, I saw your package on npm.
I was delighted to see that someone had already developed a Webpack loader for Lezer!

I just needed to configure some options so I decided to implement them all once and for all.
I didn't want to bother you with with so little changes.
If you prefer, I'd be happy to create a PR on your repository. :relaxed:  

Otherwise, it would be cool to use the same package name.
That way, everyone can benefit from the new options.

Oh, I didn't notice this slight issue in the example.
I'm changing it right now.
Don't hesitate if you see any other issue.
